### ISSUE TITLE
LiveLights Crashes when hitting (-)

### ISSUE THREAD

**Issue by mike9918** [pnwparksfan/rph-live-lights#12]
https://gyazo.com/efd6b2dc74e842a2ee43bb0d459db578

Log:

[1/9/2022 10:26:34 PM.291] Started new log on 1/9/2022 10:26:34 PM.291

[1/9/2022 10:26:34 PM.292] ====================================================================================================
[1/9/2022 10:26:34 PM.287] Log path: C:\Program Files\Rockstar Games\Grand Theft Auto V\RagePluginHook.log
[1/9/2022 10:26:34 PM.292] Log verbosity: Trivial
[1/9/2022 10:26:34 PM.293] Initializing input system
[1/9/2022 10:26:34 PM.295] Initializing game console
[1/9/2022 10:26:34 PM.301] Console key has been set to F4 (key code: 115)
[1/9/2022 10:26:34 PM.344] Initializing console variable "ConsoleScrollAmount".
[1/9/2022 10:26:34 PM.344] Type: System.Int32, Reading section: "Miscellaneous", key: ConsoleScrollAmount
[1/9/2022 10:26:34 PM.346] Read value: <null>
[1/9/2022 10:26:34 PM.346] Initializing console variable "ConsoleKey".
[1/9/2022 10:26:34 PM.346] Type: System.Windows.Forms.Keys, Reading section: "Miscellaneous", key: ConsoleKey
[1/9/2022 10:26:34 PM.346] Read value: <null>
[1/9/2022 10:26:34 PM.346] Initializing console variable "PluginTimeoutThreshold".
[1/9/2022 10:26:34 PM.346] Type: System.Int32, Reading section: "Miscellaneous", key: PluginTimeoutThreshold
[1/9/2022 10:26:34 PM.348] Read value: 10000
[1/9/2022 10:26:34 PM.348] Setting value of console variable "PluginTimeoutThreshold" to stored value.
[1/9/2022 10:26:34 PM.348] Initializing console variable "AlwaysShowConsoleOutput".
[1/9/2022 10:26:34 PM.348] Type: System.Boolean, Reading section: "Miscellaneous", key: AlwaysShowConsoleOutput
[1/9/2022 10:26:34 PM.349] Read value: <null>
[1/9/2022 10:26:34 PM.349] Initializing console variable "ShowConsoleCommandInfoOnPluginLoad".
[1/9/2022 10:26:34 PM.349] Type: System.Boolean, Reading section: "Miscellaneous", key: ShowConsoleCommandInfoOnPluginLoad
[1/9/2022 10:26:34 PM.349] Read value: <null>
[1/9/2022 10:26:34 PM.349] Initializing console variable "ShowOnScreenWarnings".
[1/9/2022 10:26:34 PM.349] Type: System.Boolean, Reading section: "Miscellaneous", key: ShowOnScreenWarnings
[1/9/2022 10:26:34 PM.349] Read value: <null>
[1/9/2022 10:26:34 PM.349] Console initialized
[1/9/2022 10:26:34 PM.349] Initializing forms manager
[1/9/2022 10:26:34 PM.350] Cleaning temp folder
[1/9/2022 10:26:34 PM.351] Version: RAGE Plugin Hook v1.90.1298.16281 for Grand Theft Auto V
[1/9/2022 10:26:34 PM.356] ================ RAGE Plugin Hook ================
[1/9/2022 10:26:34 PM.360] Detected Windows 10 Professional (64-bit) (10.0.22000.0)!
[1/9/2022 10:26:34 PM.361] Checking game support
[1/9/2022 10:26:34 PM.563] Product name: Grand Theft Auto V
[1/9/2022 10:26:34 PM.563] Product version: 1.0.2545.0
[1/9/2022 10:26:34 PM.563] Is steam version: False
[1/9/2022 10:26:34 PM.564] Initializing DirectX
[1/9/2022 10:26:34 PM.564] Initializing Direct3D
[1/9/2022 10:26:34 PM.565] Getting game swap chain
[1/9/2022 10:26:34 PM.590] Swap Chain created: 0x7FF6909BA538
[1/9/2022 10:26:34 PM.590] Swap Chain VTable: 0x152F8D46FD0
[1/9/2022 10:26:34 PM.590] 0x74894810245C8948;0x8D48564157552024;0x170EC814890246C
[1/9/2022 10:26:34 PM.590] D3D11Present: 0x7FFCF6EF14D0
[1/9/2022 10:26:34 PM.590] D3D11ResizeBuffers: 0x7FFCF6F17B20
[1/9/2022 10:26:34 PM.590] D3D11ResizeTarget: 0x7FFCF6F67280
[1/9/2022 10:26:34 PM.590] D3D11SetFullscreenState: 0x7FFCF6F186E0
[1/9/2022 10:26:34 PM.590] Direct3D initialized
[1/9/2022 10:26:34 PM.591] Initialized DirectX
[1/9/2022 10:26:34 PM.591] Direct3D watcher thread spawned
[1/9/2022 10:26:34 PM.614] Getting device
[1/9/2022 10:26:34 PM.614] Retrieved device
[1/9/2022 10:26:34 PM.614] Creating wrapper
[1/9/2022 10:26:34 PM.672] Wrapper created
[1/9/2022 10:26:34 PM.676] Effect created
[1/9/2022 10:26:34 PM.676] Creating buffer
[1/9/2022 10:26:34 PM.676] Created buffer
[1/9/2022 10:26:34 PM.676] Creating blend state
[1/9/2022 10:26:34 PM.676] Created blend state
[1/9/2022 10:26:34 PM.676] Done with creation
[1/9/2022 10:26:34 PM.984] Initializing texture system.
[1/9/2022 10:26:34 PM.984] Initializing texture system; phase 1
[1/9/2022 10:26:34 PM.984] Initializing texture system; phase 2
[1/9/2022 10:26:34 PM.990] Initializing texture system; phase 3
[1/9/2022 10:26:34 PM.990] Initializing texture system; phase 4
[1/9/2022 10:26:34 PM.999] Initializing texture system; phase 5
[1/9/2022 10:26:35 PM.000] Initializing texture system; phase 6
[1/9/2022 10:26:35 PM.001] Initializing texture system; phase 7
[1/9/2022 10:26:35 PM.002] Initializing texture system; phase 8
[1/9/2022 10:26:35 PM.004] Initializing texture system; phase 9
[1/9/2022 10:26:35 PM.004] Initializing texture system; phase 10
[1/9/2022 10:26:35 PM.006] Initializing texture system; phase 11
[1/9/2022 10:26:35 PM.007] Initializing texture system; phase 12
[1/9/2022 10:26:35 PM.008] Initializing texture system; phase 13
[1/9/2022 10:26:35 PM.008] Initializing texture system; phase 14
[1/9/2022 10:26:39 PM.592] Direct3D watcher thread ended
[1/9/2022 10:30:05 PM.455] LoadingScreenMsg: Initializing game support
[1/9/2022 10:30:05 PM.705] Initializing game support
[1/9/2022 10:30:11 PM.156] LoadingScreenMsg: Velocity limit removed
[1/9/2022 10:30:11 PM.457] Compatibility level: 0
[1/9/2022 10:30:11 PM.457] Supported version detected
[1/9/2022 10:30:11 PM.457] ==================================================
[1/9/2022 10:30:11 PM.457] LoadingScreenMsg: Patching code
[1/9/2022 10:30:11 PM.707] LoadingScreenMsg: Waiting for game initialization
[1/9/2022 10:30:11 PM.957] Waiting for game initialization
[1/9/2022 10:30:12 PM.058] LoadingScreenMsg: Initializing core
[1/9/2022 10:30:12 PM.308] Initializing hook
[1/9/2022 10:30:17 PM.328] LoadingScreenMsg: Completing interoperability
[1/9/2022 10:30:17 PM.578] Completing interoperability
[1/9/2022 10:30:17 PM.578] Initialization code 1.
[1/9/2022 10:30:17 PM.578] Initialization code 2.
[1/9/2022 10:30:17 PM.578] Initialization code 3.
[1/9/2022 10:30:17 PM.584] 1 Address: 0x00007FF68E82B16C
[1/9/2022 10:30:17 PM.584] Calling func 1
[1/9/2022 10:30:17 PM.597] 2 Address: 0x00007FF68F3D6B9E
[1/9/2022 10:30:17 PM.597] 3 Address: 0x00007FF68DDF5EF6
[1/9/2022 10:30:17 PM.620] Address: 0x00007FF68F3D6B48
[1/9/2022 10:30:17 PM.620] Unknown var: 0x00007FF690449790
[1/9/2022 10:30:17 PM.620] Initialization code 4.
[1/9/2022 10:30:17 PM.620] Initialization code 5.
[1/9/2022 10:30:17 PM.620] Completing interoperability, phase 1
[1/9/2022 10:30:17 PM.620] Completing interoperability, phase 2
[1/9/2022 10:30:17 PM.620] Completing interoperability, phase 3
[1/9/2022 10:30:17 PM.620] Completing interoperability, phase 4
[1/9/2022 10:30:17 PM.620] Completing interoperability, phase 5
[1/9/2022 10:30:17 PM.620] Completing interoperability, phase 6
[1/9/2022 10:30:17 PM.620] Completing interoperability, phase 7
[1/9/2022 10:30:17 PM.620] LoadingScreenMsg: 
[1/9/2022 10:30:17 PM.871] LoadingScreenMsg: Loading Story Mode
[1/9/2022 10:30:20 PM.040] LoadingScreenMsg: Loading and Populating Game World
[1/9/2022 10:30:20 PM.291] LoadingScreenMsg: 
[1/9/2022 10:30:33 PM.967] Initializing console variable "IsDeveloperModeEnabled".
[1/9/2022 10:30:33 PM.967] Type: System.Boolean, Reading section: "Miscellaneous", key: IsDeveloperModeEnabled
[1/9/2022 10:30:33 PM.967] Read value: <null>
[1/9/2022 10:30:33 PM.967] Initializing console variable "TimeScale".
[1/9/2022 10:30:33 PM.967] Type: System.Single, Reading section: "Miscellaneous", key: TimeScale
[1/9/2022 10:30:33 PM.968] Read value: <null>
[1/9/2022 10:30:33 PM.975] Loading plugin from path: C:\Program Files\Rockstar Games\Grand Theft Auto V\Plugins\LiveLights.dll
[1/9/2022 10:30:35 PM.874] <UNLOADED PLUGIN>: Initializing input system
[1/9/2022 10:30:35 PM.875] <UNLOADED PLUGIN>: Initializing game console
[1/9/2022 10:30:35 PM.876] <UNLOADED PLUGIN>: Initializing forms manager
[1/9/2022 10:30:35 PM.925] Plugin "Live Carcols and Siren Editor" was loaded from "LiveLights.dll".
[1/9/2022 10:30:36 PM.122] Live Carcols and Siren Editor: Detected RPH 1.90.1298.16281
[1/9/2022 10:30:36 PM.122] Live Carcols and Siren Editor: Loaded LiveLights 0.7.7534.881
[1/9/2022 10:30:36 PM.155] Live Carcols and Siren Editor: Added color option Red Halogen = 0xFFFF1405
[1/9/2022 10:30:36 PM.155] Live Carcols and Siren Editor: Added color option Blue Halogen = 0xFF2130FF
[1/9/2022 10:30:36 PM.155] Live Carcols and Siren Editor: Added color option Red LED = 0xFFFF0300
[1/9/2022 10:30:36 PM.155] Live Carcols and Siren Editor: Added color option Blue LED = 0xFF000AFF
[1/9/2022 10:30:36 PM.155] Live Carcols and Siren Editor: Added color option Amber = 0xFFFF4800
[1/9/2022 10:30:36 PM.155] Live Carcols and Siren Editor: Added color option White = 0xFFFFFFFF
[1/9/2022 10:30:36 PM.155] Live Carcols and Siren Editor: Press OemMinus to open the menu
[1/9/2022 10:30:37 PM.201] Live Carcols and Siren Editor: Retrieved full release list
[1/9/2022 10:30:37 PM.201] Live Carcols and Siren Editor: Latest release on github: v0.7-rc
[1/9/2022 10:30:37 PM.201] Live Carcols and Siren Editor: Current version is up to date
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: 
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: ==============================
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: Origin: Game fiber "Plugin "Live Carcols and Siren Editor" main fiber".
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: Exception type: System.AccessViolationException
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: Exception message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: Inner exceptions:
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: Stack trace:
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: at RAGENativeUI.IL.Invoker.InvokeRetFloat(IntPtr fnPtr) in D:\a\RAGENativeUI\RAGENativeUI\Source\Internals\ModuleInitializer.cs:line 0
[1/9/2022 10:33:34 PM.817] at RAGENativeUI.Internals.Screen.get_ActualResolution() in D:\a\RAGENativeUI\RAGENativeUI\Source\Internals\Memory.cs:line 317
[1/9/2022 10:33:34 PM.817] at RAGENativeUI.UIMenu.get_AdjustedWidth() in D:\a\RAGENativeUI\RAGENativeUI\Source\UIMenu.cs:line 362
[1/9/2022 10:33:34 PM.817] at RAGENativeUI.UIMenu.Draw() in D:\a\RAGENativeUI\RAGENativeUI\Source\UIMenu.cs:line 698
[1/9/2022 10:33:34 PM.817] at RAGENativeUI.MenuPool.ProcessMenus() in D:\a\RAGENativeUI\RAGENativeUI\Source\MenuPool.cs:line 160
[1/9/2022 10:33:34 PM.817] at Rage.GameFiber.GameFiberExecuteHelper.Execute()
[1/9/2022 10:33:34 PM.817] at Rage.GameFiber.ExecuteWhile(ThreadStart start, Func`1 condition)
[1/9/2022 10:33:34 PM.817] at LiveLights.EntryPoint.Main() in C:\GTA Dev\devel\projects\LiveLights\LiveLights\EntryPoint.cs:line 65
[1/9/2022 10:33:34 PM.817] at Rage.GameFiber.Main()
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: ==============================
[1/9/2022 10:33:34 PM.817] Live Carcols and Siren Editor: 
[1/9/2022 10:34:48 PM.683] Loading plugin from path: C:\Program Files\Rockstar Games\Grand Theft Auto V\Plugins\LiveLights.dll
[1/9/2022 10:34:50 PM.520] <UNLOADED PLUGIN>: Initializing input system
[1/9/2022 10:34:50 PM.520] <UNLOADED PLUGIN>: Initializing game console
[1/9/2022 10:34:50 PM.521] <UNLOADED PLUGIN>: Initializing forms manager
[1/9/2022 10:34:50 PM.561] Plugin "Live Carcols and Siren Editor" was loaded from "LiveLights.dll".
[1/9/2022 10:34:50 PM.594] Live Carcols and Siren Editor: Detected RPH 1.90.1298.16281
[1/9/2022 10:34:50 PM.594] Live Carcols and Siren Editor: Loaded LiveLights 0.7.7534.881
[1/9/2022 10:34:50 PM.616] Live Carcols and Siren Editor: Added color option Red Halogen = 0xFFFF1405
[1/9/2022 10:34:50 PM.617] Live Carcols and Siren Editor: Added color option Blue Halogen = 0xFF2130FF
[1/9/2022 10:34:50 PM.617] Live Carcols and Siren Editor: Added color option Red LED = 0xFFFF0300
[1/9/2022 10:34:50 PM.617] Live Carcols and Siren Editor: Added color option Blue LED = 0xFF000AFF
[1/9/2022 10:34:50 PM.617] Live Carcols and Siren Editor: Added color option Amber = 0xFFFF4800
[1/9/2022 10:34:50 PM.617] Live Carcols and Siren Editor: Added color option White = 0xFFFFFFFF
[1/9/2022 10:34:50 PM.617] Live Carcols and Siren Editor: Press OemMinus to open the menu
[1/9/2022 10:34:51 PM.551] Live Carcols and Siren Editor: Retrieved full release list
[1/9/2022 10:34:51 PM.551] Live Carcols and Siren Editor: Latest release on github: v0.7-rc
[1/9/2022 10:34:51 PM.551] Live Carcols and Siren Editor: Current version is up to date
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: 
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: ==============================
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: Origin: Game fiber "Plugin "Live Carcols and Siren Editor" main fiber".
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: Exception type: System.AccessViolationException
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: Exception message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: Inner exceptions:
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: ------------------------------
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: Stack trace:
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: at RAGENativeUI.IL.Invoker.InvokeRetFloat(IntPtr fnPtr) in D:\a\RAGENativeUI\RAGENativeUI\Source\Internals\ModuleInitializer.cs:line 0
[1/9/2022 10:34:53 PM.950] at RAGENativeUI.Internals.Screen.get_ActualResolution() in D:\a\RAGENativeUI\RAGENativeUI\Source\Internals\Memory.cs:line 317
[1/9/2022 10:34:53 PM.950] at RAGENativeUI.UIMenu.get_AdjustedWidth() in D:\a\RAGENativeUI\RAGENativeUI\Source\UIMenu.cs:line 362
[1/9/2022 10:34:53 PM.950] at RAGENativeUI.UIMenu.Draw() in D:\a\RAGENativeUI\RAGENativeUI\Source\UIMenu.cs:line 698
[1/9/2022 10:34:53 PM.950] at RAGENativeUI.MenuPool.ProcessMenus() in D:\a\RAGENativeUI\RAGENativeUI\Source\MenuPool.cs:line 160
[1/9/2022 10:34:53 PM.950] at Rage.GameFiber.GameFiberExecuteHelper.Execute()
[1/9/2022 10:34:53 PM.950] at Rage.GameFiber.ExecuteWhile(ThreadStart start, Func`1 condition)
[1/9/2022 10:34:53 PM.950] at LiveLights.EntryPoint.Main() in C:\GTA Dev\devel\projects\LiveLights\LiveLights\EntryPoint.cs:line 65
[1/9/2022 10:34:53 PM.950] at Rage.GameFiber.Main()
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: ==============================
[1/9/2022 10:34:53 PM.950] Live Carcols and Siren Editor: 
[1/9/2022 10:36:19 PM.371] Unknown command or variable "quit"
[1/9/2022 10:36:21 PM.269] Exiting...
`

**Comment by pnwparksfan** [comment]
Update RageNativeUI
